name: pgn_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper : ^1.1.6
  firebase_messaging: ^7.0.3
  # firebase_messaging: ^5.1.5
  intl: ^0.17.0
  image_picker: ^0.6.7+22 # need to configure Info.plist for iOS
  carousel_pro: ^1.0.0
  charts_flutter: ^0.10.0
  device_info: ^0.4.0+2
  http: ^0.12.2
  # shared_preferences: 0.5.7+3
  shared_preferences: ^2.0.6
  flutter_secure_storage: ^4.2.1
  encrypted_shared_preferences: ^2.0.0
  google_maps_flutter: ^0.5.5
  font_awesome_flutter: ^8.12.0
  provider: ^5.0.0
  liquid_pull_to_refresh: ^1.1.1
  dotted_decoration: ^2.0.0
  # fl_chart: ^0.8.0
  url_launcher: ^5.0.3
  rflutter_alert: ^1.0.2
  percent_indicator: ^2.1.1
  # flutter_webview_plugin: 0.3.0+2
  # flutter_money_formatter: ^0.8.3
  # pull_to_refresh: ^1.5.4
  expandable: ^4.1.4
  flutter_gifimage: ^1.0.0
  flutter_launcher_icons: ^0.9.1
  encrypt: ^5.0.0
  date_format: ^1.0.8
  otp_text_field: ^1.1.1
  fluttertoast: ^8.0.3
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: ^1.0.1
  custom_switch: ^0.0.1
  # webview_flutter: ^0.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
  #   image_path_ios: "assets/launcher/icon.png"
#   image_path_android: "assets/launcher/icon.png"
#   adaptive_icon_background: "assets/launcher/background.png"
#   adaptive_icon_foreground: "assets/launcher/foreground.png"
